# Workflow to build and test wheels
name: Wheel builder

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.python }}-${{ matrix.os }}-{{ matrix.manylinux_image}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python: 38
        bitness: [64]
        manylinux_image: [manylinux2010]
        include:
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64

    steps:
      - name: Checkout tempo
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.3

      - name: Build and test wheels
        env: 
          CIBW_BUILD:  cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: .wheelhouse/*.whl
