# Workflow to build and test wheels
name: Wheel builder

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tempo
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install wheel
        run: python -m pip install wheel

      - name: Build wheel
        run: cd python && python setup.py bdist_wheel

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: python/dist/*.whl
